### ISSUE TITLE
CRITICAL Uncaught Error: Cannot use object of type WP_Error as array

### ISSUE THREAD

**Issue by leanderhamzoui** [WeProgramIT/cryptowoo-monero-addon#25]
in regards to the other issue about xmrchain i tried updating to 1.2.0. from i think 1.1.2

upon checkout, the user is no longer presented with xmr address, but rather with:
"There has been a critical error on this website."

backend log:

2022-11-11T13:55:40+00:00 CRITICAL Uncaught Error: Cannot use object of type WP_Error as array in /var/www/html/wp-content/plugins/cryptowoo-monero-addon/includes/monerowp/library.php:330
Stack trace:
#0 /var/www/html/wp-content/plugins/cryptowoo-monero-addon/cryptowoo-monero-addon.php(309): NodeTools->get_last_block_height()
#1 /var/www/html/wp-includes/class-wp-hook.php(308): cwxmr_get_payment_address()
#2 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /var/www/html/wp-content/plugins/cryptocurrency-payment-gateway/cryptocurrency-payment-gateway.php(1016): apply_filters()
#4 /var/www/html/wp-content/plugins/cryptocurrency-payment-gateway/cryptocurrency-payment-gateway.php(818): WC_CryptoWoo->generate_cryptowoo_form()
#5 /var/www/html/wp-includes/class-wp-hook.php(308): WC_CryptoWoo->receipt_page()
#6 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/html/wp-content/plugins/woocommerce/templates/checkout/order-receip in /var/www/html/wp-content/plugins/cryptowoo-monero-addon/includes/monerowp/library.php on line 330

**Comment by leanderhamzoui** [comment]
I was able to resolve the error by
downgrading to 1.1.1
go to monero page where payment address and view key is set, i just saved it again
-> worked

i then upgraded to 1.2.0
-> still worked

so not sure what caused the above mentioned error at the beginning.

**Comment by leanderhamzoui** [comment]
Resolved with 1.3.0
