### ISSUE TITLE
cw_get_option no longer exists in CryptoWoo 0.25.21

### ISSUE THREAD

**Issue by normana10** [WeProgramIT/cryptowoo-monero-addon#28]
I just updated my CryptoWoo plugin to latest (0.25.21) and the whole site crashes on line 167 of `cryptowoo-monero-addon.php`

I'm on version 1.3.0 of the CryptoWoo Monero Add-on

Thanks!

Stacktrace:
[03-Dec-2022 02:25:15 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function cw_get_option() in /home/user/public_html/wp-content/plugins/cryptowoo-monero-addon/cryptowoo-monero-addon.php:167
Stack trace:
#0 /home/user/public_html/wp-includes/class-wp-hook.php(307): {closure}('')
#1 /home/user/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/user/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /home/user/public_html/wp-settings.php(461): do_action('plugins_loaded')
#4 /home/user/public_html/wp-config.php(106): require_once('/home/user...')
#5 /home/user/public_html/wp-load.php(50): require_once('/home/user...')
#6 /home/user/public_html/wp-blog-header.php(13): require_once('/home/user...')
#7 /home/user/public_html/index.php(17): require('/home/user...')
#8 {main}
  thrown in /home/user/public_html/wp-content/plugins/cryptowoo-monero-addon/cryptowoo-monero-addon.php on line 167

**Comment by Olsm** [comment]
Hi there,

You're using an outdated version of CryptoWoo. We migrated over to the WordPress Plugin Directory in February. You can read about why we did this and how you can update here: https://www.cryptowoo.com/blog/cryptowoo-migrates-to-the-wordpress-plugin-directory/

**Comment by Olsm** [comment]
Do not hesitate to contact our support channel if you are having any issues in getting updated, at https://cryptowoo.zendesk.com/.

We sent an email to our customer base about this as well as posted publicly when this happened, but we would like to avoid this issue happening for other users as well and we understand this may not be visible for everyone.

In that regard, I would appreciate if you could share with us why you thought this version was the latest version? Am I correct in assuming you accessed your my-account page on our website and downloaded the latest version from there? I see we are lacking any kind of warning here that this is not the latest version and to link to the new version.

**Comment by Olsm** [comment]
Thanks for clarifying and you are right, we should add this compatibility check with an admin notice instructing to update the main plugin. I will reopen this issue and rename it a bit to keep track of the progress on it. Thanks so much for your detailed feedback and suggestion.
